import { create } from 'zustand'

const STORAGE_KEY = 'language'

const translations = {
  ru: {
    common: {
      attention: 'Обратите внимание',
      done: 'Готово',
      info: 'Информация',
      retry: 'Повторить',
      closeMessage: 'Скрыть сообщение',
      saveInProgress: 'Сохранение...',
      deleteConfirm: 'Удалить запись?',
    },
    navbar: {
      air: 'Эфир',
      panel: 'Панель',
      admin: 'Админка',
      logout: 'Выход',
      switchLanguage: 'Сменить язык',
      toggleTheme: 'Переключить тему',
    },
    auth: {
      loginTitle: 'Вход в систему',
      loginSubtitle: 'Доступ к системе вещания',
      login: 'Логин',
      fio: 'ФИО',
      password: 'Пароль',
      confirmPassword: 'Подтверждение пароля',
      loginButton: 'Войти',
      registerButton: 'Зарегистрироваться',
      registerTitle: 'Регистрация',
      registerSubtitle: 'Регистрация учетной записи',
      noAccount: 'Нет аккаунта?',
      register: 'Зарегистрироваться',
      hasAccount: 'Уже есть аккаунт?',
      loginLink: 'Войти',
      loginPlaceholder: 'Введите ваш логин',
      passwordPlaceholder: 'Введите ваш пароль',
      loginLatinOnly: 'Только латинские буквы',
      fioPlaceholder: 'Иванов Иван Иванович',
      fioHint: 'Только русские буквы и пробелы',
      passwordHint: 'Минимум 4 символа',
      confirmPasswordPlaceholder: 'Повторите пароль',
      platformName: 'Платформа потокового вещания',
      loginError: 'Ошибка входа',
      registerError: 'Ошибка регистрации',
      loginRule: 'Логин должен содержать только латинские буквы',
      fioRule: 'ФИО должно содержать только русские буквы',
      passwordRule: 'Пароль может содержать только латинские буквы, цифры и символы',
      passwordMinRule: 'Пароль должен быть не менее 4 символов',
      passwordMismatch: 'Пароли не совпадают',
    },
    player: {
      title: 'Прямой эфир',
      subtitle: 'Синхронизированное воспроизведение текущего эфира.',
      volume: 'Громкость',
      onAir: 'В эфире',
      waitingForAir: 'Ожидание эфира',
      noTrack: 'Нет активного трека',
      player: 'Плеер',
      live: 'В эфире',
      messages: 'Сообщения',
      send: 'Отправить',
      recordVoice: 'Записать голос',
      stop: 'Стоп',
      recording: 'Идет запись...',
      noMessages: 'Нет сообщений',
      communication: 'Связь с ведущим',
      messagePlaceholder: 'Введите текст сообщения...',
      sendRecording: 'Отправить запись',
      noBroadcast: 'Вещание отсутствует',
      waitForBroadcast: 'Ожидайте начала прямого эфира',
      textSendError: 'Не удалось отправить текстовое сообщение.',
      voiceSendError: 'Не удалось отправить голосовое сообщение.',
      micAccessError: 'Доступ к микрофону не предоставлен. Разрешите его в настройках браузера и повторите попытку.',
      videoStream: 'Видеотрансляция',
      syncedAudioStream: 'Синхронный аудиопоток',
      play: 'Воспроизвести',
      pause: 'Пауза',
      micRetry: 'Повторить запрос',
      micUnavailable: 'Микрофон недоступен',
    },
    host: {
      title: 'Панель ведущего',
      description: 'Управление эфиром, плейлистами и сообщениями слушателей.',
      onAir: 'В эфире',
      broadcastStopped: 'Эфир остановлен',
      playlist: 'Плейлист',
      monitoring: 'Мониторинг',
      startBroadcast: 'Начать вещание',
      stopBroadcast: 'Остановить эфир',
      playlists: 'Плейлисты',
      tracks: 'Треки',
      mediaLibrary: 'Медиатека',
      addToPlaylist: 'В плейлист',
      delete: 'Удалить',
      monitorTitle: 'Монитор эфира',
      monitorDescription: 'Локальное прослушивание ведущего работает отдельно от публичного плеера.',
      previous: 'Назад',
      next: 'Вперёд',
      enableMonitoring: 'Включить мониторинг',
      disableMonitoring: 'Выключить мониторинг',
      monitoringVolume: 'Громкость мониторинга',
      monitoringSyncing: 'Локальный мониторинг синхронизируется',
      monitoringActive: 'Мониторинг активен',
      monitoringWaiting: 'Ожидание воспроизведения',
      monitoringDisabled: 'Мониторинг выключен',
      noBroadcastYet: 'Эфир ещё не запущен.',
      notSelected: 'не выбран',
      enabled: 'включён',
      disabled: 'выключен',
      activateForAir: 'Активировать для эфира',
      loopOn: 'ВКЛ',
      loopOff: 'ВЫКЛ',
      shuffleOn: 'ВКЛ',
      shuffleOff: 'ВЫКЛ',
      tracksInPlaylist: 'Треки в плейлисте',
      nowOnAir: 'Сейчас в эфире',
      audioAir: 'Аудиоэфир',
      videoAir: 'Видеоэфир',
      createPlaylistPlaceholder: 'Название плейлиста',
      create: 'Создать',
      cancel: 'Отмена',
      archive: 'Архив',
      back: 'Назад',
      tracksCount: 'Треков',
      active: 'Активен',
      recordFromMic: 'Записать с микрофона',
      saveMicRecordingError: 'Не удалось сохранить запись с микрофона.',
      micAccessError: 'Доступ к микрофону не предоставлен. Разрешите его в настройках браузера и повторите попытку.',
      loadError: 'Не удалось загрузить данные ведущего. Попробуйте обновить страницу.',
      uploadError: 'Не удалось загрузить файл в медиатеку.',
      deleteFileError: 'Не удалось удалить файл из медиатеки.',
      deletePlaylistError: 'Не удалось удалить плейлист.',
      deleteFileConfirm: 'Удалить файл?',
      deletePlaylistConfirm: 'Удалить плейлист?',
      createPlaylistPrompt: 'Введите название плейлиста, прежде чем создавать его.',
      createPlaylistError: 'Не удалось создать плейлист.',
      selectPlaylistFirst: 'Сначала выберите плейлист слева, а потом добавляйте в него треки.',
      addTrackError: 'Не удалось добавить трек в плейлист.',
      activatePlaylistError: 'Не удалось активировать выбранный плейлист.',
      startBroadcastError: 'Не удалось запустить вещание.',
      stopBroadcastError: 'Не удалось остановить эфир.',
      previousTrackError: 'Не удалось переключить эфир на предыдущий трек.',
      nextTrackError: 'Не удалось переключить эфир на следующий трек.',
      selectTrackError: 'Не удалось выбрать этот трек для эфира.',
    },
    admin: {
      title: 'Администрирование',
      description: 'Управление пользователями, ролями и доступом.',
      users: 'Пользователи',
      roles: 'Роли',
      usersCount: 'Пользователей',
      rolesCount: 'Ролей',
      login: 'Логин',
      fio: 'ФИО',
      role: 'Роль',
      status: 'Статус',
      actions: 'Действия',
      apply: 'Применить',
      reset: 'Сброс',
      search: 'Поиск',
      active: 'Активен',
      blocked: 'Заблокирован',
      edit: 'Редактировать профиль',
      changePassword: 'Сменить пароль',
      assignRoles: 'Назначить роли',
      block: 'Заблокировать',
      unblock: 'Разблокировать',
      save: 'Сохранить',
      cancel: 'Отмена',
      registrationDate: 'Дата регистрации',
      allRoles: 'Все роли',
      noUsers: 'Пользователи не найдены',
      editUser: 'Редактирование пользователя',
      passwordModalTitle: 'Смена пароля',
      rolesModalTitle: 'Назначение ролей',
      newPassword: 'Новый пароль',
      roleRule: 'Пользователь не совмещается с ведущим и администратором. Администратор может дополнительно быть ведущим.',
      selected: 'Выбрано',
      assign: 'Назначить',
      noRoleDescription: 'Роль без описания',
      deleteUser: 'Удалить пользователя',
      deleteUserError: 'Не удалось удалить пользователя.',
      deleteConfirm: 'Удалить пользователя?',
      changeStatusError: 'Не удалось изменить статус пользователя.',
      saveError: 'Не удалось сохранить изменения.',
      loadUsersError: 'Не удалось загрузить пользователей.',
      loadRolesError: 'Не удалось загрузить роли.',
    },
    roles: {
      user: 'Пользователь',
      host: 'Ведущий',
      admin: 'Администратор',
      userDescription: 'Доступ к эфиру и отправке сообщений.',
      hostDescription: 'Управление медиатекой, плейлистами и эфиром.',
      adminDescription: 'Администрирование пользователей и прав доступа.',
    },
    messageStatus: {
      new: 'Новое',
      inProgress: 'В работе',
      completed: 'Завершено',
      takeInProgress: 'В работу',
      finish: 'Завершить',
    },
  },
  en: {
    common: {
      attention: 'Please note',
      done: 'Done',
      info: 'Information',
      retry: 'Retry',
      closeMessage: 'Dismiss message',
      saveInProgress: 'Saving...',
      deleteConfirm: 'Delete item?',
    },
    navbar: {
      air: 'Air',
      panel: 'Studio',
      admin: 'Admin',
      logout: 'Logout',
      switchLanguage: 'Switch language',
      toggleTheme: 'Toggle theme',
    },
    auth: {
      loginTitle: 'Sign In',
      loginSubtitle: 'Access to the broadcasting system',
      login: 'Login',
      fio: 'Full name',
      password: 'Password',
      confirmPassword: 'Confirm password',
      loginButton: 'Sign In',
      registerButton: 'Register',
      registerTitle: 'Registration',
      registerSubtitle: 'Create an account',
      noAccount: 'No account?',
      register: 'Register',
      hasAccount: 'Already have an account?',
      loginLink: 'Sign In',
      loginPlaceholder: 'Enter your login',
      passwordPlaceholder: 'Enter your password',
      loginLatinOnly: 'Latin letters only',
      fioPlaceholder: 'Ivanov Ivan Ivanovich',
      fioHint: 'Cyrillic letters and spaces only',
      passwordHint: 'Minimum 4 characters',
      confirmPasswordPlaceholder: 'Repeat your password',
      platformName: 'Streaming platform',
      loginError: 'Login failed',
      registerError: 'Registration failed',
      loginRule: 'Login must contain Latin letters only',
      fioRule: 'Full name must contain Cyrillic letters only',
      passwordRule: 'Password may contain Latin letters, digits and symbols only',
      passwordMinRule: 'Password must be at least 4 characters long',
      passwordMismatch: 'Passwords do not match',
    },
    player: {
      title: 'Live Broadcast',
      subtitle: 'Synchronized playback of the current broadcast.',
      volume: 'Volume',
      onAir: 'On air',
      waitingForAir: 'Waiting for broadcast',
      noTrack: 'No active track',
      player: 'Player',
      live: 'LIVE',
      messages: 'Messages',
      send: 'Send',
      recordVoice: 'Record voice',
      stop: 'Stop',
      recording: 'Recording...',
      noMessages: 'No messages',
      communication: 'Contact the host',
      messagePlaceholder: 'Enter your message...',
      sendRecording: 'Send recording',
      noBroadcast: 'Broadcast is offline',
      waitForBroadcast: 'Please wait for the live broadcast to start',
      textSendError: 'Failed to send the text message.',
      voiceSendError: 'Failed to send the voice message.',
      micAccessError: 'Microphone access was not granted. Allow it in your browser settings and try again.',
      videoStream: 'Video stream',
      syncedAudioStream: 'Synchronized audio stream',
      play: 'Play',
      pause: 'Pause',
      micRetry: 'Request access again',
      micUnavailable: 'Microphone unavailable',
    },
    host: {
      title: 'Host Panel',
      description: 'Manage broadcast, playlists and listener messages.',
      onAir: 'On air',
      broadcastStopped: 'Broadcast stopped',
      playlist: 'Playlist',
      monitoring: 'Monitoring',
      startBroadcast: 'Start broadcast',
      stopBroadcast: 'Stop broadcast',
      playlists: 'Playlists',
      tracks: 'Tracks',
      mediaLibrary: 'Media library',
      addToPlaylist: 'Add to playlist',
      delete: 'Delete',
      monitorTitle: 'Broadcast monitor',
      monitorDescription: 'Local host monitoring works independently from the public player.',
      previous: 'Previous',
      next: 'Next',
      enableMonitoring: 'Enable monitoring',
      disableMonitoring: 'Disable monitoring',
      monitoringVolume: 'Monitoring volume',
      monitoringSyncing: 'Local monitoring is synchronizing',
      monitoringActive: 'Monitoring is active',
      monitoringWaiting: 'Waiting for playback',
      monitoringDisabled: 'Monitoring is disabled',
      noBroadcastYet: 'Broadcast has not started yet.',
      notSelected: 'not selected',
      enabled: 'enabled',
      disabled: 'disabled',
      activateForAir: 'Activate for broadcast',
      loopOn: 'ON',
      loopOff: 'OFF',
      shuffleOn: 'ON',
      shuffleOff: 'OFF',
      tracksInPlaylist: 'Playlist tracks',
      nowOnAir: 'Now on air',
      audioAir: 'Audio broadcast',
      videoAir: 'Video broadcast',
      createPlaylistPlaceholder: 'Playlist name',
      create: 'Create',
      cancel: 'Cancel',
      archive: 'Archive',
      back: 'Back',
      tracksCount: 'Tracks',
      active: 'Active',
      recordFromMic: 'Record from microphone',
      saveMicRecordingError: 'Failed to save the microphone recording.',
      micAccessError: 'Microphone access was not granted. Allow it in your browser settings and try again.',
      loadError: 'Failed to load host data. Please refresh the page.',
      uploadError: 'Failed to upload the file to the media library.',
      deleteFileError: 'Failed to delete the file from the media library.',
      deletePlaylistError: 'Failed to delete the playlist.',
      deleteFileConfirm: 'Delete file?',
      deletePlaylistConfirm: 'Delete playlist?',
      createPlaylistPrompt: 'Enter a playlist name before creating it.',
      createPlaylistError: 'Failed to create the playlist.',
      selectPlaylistFirst: 'Select a playlist first, then add tracks to it.',
      addTrackError: 'Failed to add the track to the playlist.',
      activatePlaylistError: 'Failed to activate the selected playlist.',
      startBroadcastError: 'Failed to start broadcasting.',
      stopBroadcastError: 'Failed to stop broadcasting.',
      previousTrackError: 'Failed to switch to the previous track.',
      nextTrackError: 'Failed to switch to the next track.',
      selectTrackError: 'Failed to select this track for broadcast.',
    },
    admin: {
      title: 'Administration',
      description: 'Manage users, roles and access.',
      users: 'Users',
      roles: 'Roles',
      usersCount: 'Users',
      rolesCount: 'Roles',
      login: 'Login',
      fio: 'Full name',
      role: 'Role',
      status: 'Status',
      actions: 'Actions',
      apply: 'Apply',
      reset: 'Reset',
      search: 'Search',
      active: 'Active',
      blocked: 'Blocked',
      edit: 'Edit profile',
      changePassword: 'Change password',
      assignRoles: 'Assign roles',
      block: 'Block',
      unblock: 'Unblock',
      save: 'Save',
      cancel: 'Cancel',
      registrationDate: 'Registration date',
      allRoles: 'All roles',
      noUsers: 'No users found',
      editUser: 'Edit user',
      passwordModalTitle: 'Change password',
      rolesModalTitle: 'Assign roles',
      newPassword: 'New password',
      roleRule: 'A basic user role cannot be combined with host or admin. An admin may also be a host.',
      selected: 'Selected',
      assign: 'Assign',
      noRoleDescription: 'Role without description',
      deleteUser: 'Delete user',
      deleteUserError: 'Failed to delete the user.',
      deleteConfirm: 'Delete user?',
      changeStatusError: 'Failed to update the user status.',
      saveError: 'Failed to save changes.',
      loadUsersError: 'Failed to load users.',
      loadRolesError: 'Failed to load roles.',
    },
    roles: {
      user: 'User',
      host: 'Host',
      admin: 'Administrator',
      userDescription: 'Access to the broadcast and message sending.',
      hostDescription: 'Manage media library, playlists and broadcast.',
      adminDescription: 'Manage users and access rights.',
    },
    messageStatus: {
      new: 'New',
      inProgress: 'In progress',
      completed: 'Completed',
      takeInProgress: 'Take',
      finish: 'Complete',
    },
  },
}

function resolveTranslation(language, path) {
  return path.split('.').reduce((value, key) => value?.[key], translations[language])
}

const initialLanguage =
  typeof window !== 'undefined' ? localStorage.getItem(STORAGE_KEY) || 'ru' : 'ru'

export const useLanguage = create((set, get) => ({
  language: initialLanguage,
  setLanguage: (language) => {
    const nextLanguage = language === 'en' ? 'en' : 'ru'
    if (typeof window !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, nextLanguage)
    }
    if (typeof document !== 'undefined') {
      document.documentElement.setAttribute('lang', nextLanguage)
    }
    set({ language: nextLanguage })
  },
  toggleLanguage: () => {
    const nextLanguage = get().language === 'ru' ? 'en' : 'ru'
    get().setLanguage(nextLanguage)
  },
  t: (path) => {
    const currentLanguage = get().language
    const translated = resolveTranslation(currentLanguage, path)
    if (typeof translated === 'string') {
      return translated
    }
    const fallback = resolveTranslation('ru', path)
    return typeof fallback === 'string' ? fallback : path
  },
}))

export function getLocale(language) {
  return language === 'en' ? 'en-US' : 'ru-RU'
}
